language: node_js
notifications:
  email: 
    - noyobo@gmail.com
node_js:
  - '0.12'
before_script:
  - npm install blanket istanbul coveralls
script: "npm run test"
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage